#ifndef ROOTKIT_LINUX_H
#define ROOTKIT_LINUX_H

#include <inttypes.h>

#define UEFI_HEADER_VALUE 0x91005a4d
#define NS_IMAGE_OFFSET 0x40000000ul

#define TASK_COMM_LEN 16
#define INIT_TASK_COMM "swapper/0"

#define TASK_STRUCT_NUM_SIGNATURES 3
#define TASK_STRUCT_SIGNATURE_LENGTH 20
#define TASK_STRUCT_SIGNATURE_OFFSET 4
extern const uint8_t TASK_STRUCT_SIGNATURE[TASK_STRUCT_NUM_SIGNATURES][TASK_STRUCT_SIGNATURE_LENGTH];

#define NUM_CREDS 2

#define NUM_COUNTED_STATES 2
#define MIN_STATE_OCCURRENCES 3
extern const uint64_t STATE_MAPPING[NUM_COUNTED_STATES];

typedef int pid_t;

#endif
